use crate::config::SpdeDefaults;
use crate::scheduler::NodeTask;
use uuid::Uuid;

/// 生成节点可直接使用的 SPDE config.yaml
///
/// 控制面完全通过此文件下发：agent 段告诉节点 master 地址与心跳间隔，
/// direct_tasks 列出该节点应执行的全部任务（含 dispatch_id 用于回报告）。
/// SPDE 对比 config_version 决定是否重拉。
pub fn render_config(
    defaults: &SpdeDefaults,
    tasks: &[NodeTask],
    master: &str,
    node_id: Uuid,
    heartbeat_interval_secs: u64,
) -> String {
    let mut yaml = format!(
        r#"# generated by PK master — do not edit by hand if agent-managed
agent:
  master: {:?}
  node_id: {:?}
  heartbeat_interval_secs: {}

global:
  work_dir: null
  max_concurrent: {}
  resume: {}
  retry_times: {}
  timeout: {}
  skip_tls_verify: {}
  connections_per_file: {}
  dry_run: {}

output:
  save_path: {:?}

proxy:
  http_proxy: {:?}
  https_proxy: {:?}

direct_tasks:
"#,
        master,
        node_id,
        heartbeat_interval_secs,
        defaults.max_concurrent,
        defaults.resume,
        defaults.retry_times,
        defaults.timeout,
        defaults.skip_tls_verify,
        defaults.connections_per_file,
        defaults.dry_run,
        defaults.save_path,
        defaults.http_proxy,
        defaults.https_proxy,
    );

    let enabled: Vec<&NodeTask> = tasks.iter().filter(|nt| nt.task.enable).collect();
    if enabled.is_empty() {
        yaml.push_str("  []\n");
        return yaml;
    }
    for nt in enabled {
        yaml.push_str(&format!(
            "  - name: {}\n    enable: true\n    url: {}\n    filename: {}\n    task_id: {}\n    dispatch_id: {}\n",
            yaml_quote(&nt.task.name),
            yaml_quote(&nt.task.url),
            yaml_quote(&nt.task.filename),
            nt.task.id,
            nt.dispatch_id,
        ));
    }
    yaml
}

fn yaml_quote(s: &str) -> String {
    serde_yaml::to_string(s)
        .unwrap_or_else(|_| format!("\"{}\"", s.replace('"', "\\\"")))
        .trim()
        .to_string()
}
