name: Release PK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: PandaNetOS/PandaNetOS/.github/workflows/reusable-release-rust-binary.yml@main
    with:
      binary_name: pk
      project_name: PK
      dispatch_downstream: true
      downstream_repo: pcdn-keeper
    secrets: inherit
